### PR TITLE
Fix make

### PR DESCRIPTION
**Pull request by alistairewj**
Fix various syntax errors across queries and propagate recent changes to PostgreSQL.

### CODE REVIEW

**Comment by chaoXO** [comment]
\i medication/milrinone.sql
\i medication/vasoactive_agent.sql
\i medication/norepinephrine_equivalent_dose.sql

these three files don't exist in mimic-iv\concepts\postgres\medication,
can i just copy the files from mimic-iv\concepts\medication

**Comment by alistairewj** [comment]
Some syntax changes are required. There is a shell script that applies them, and you can look there for an idea of what is necessary.

The files should have been included, I just tend to forget to generate postgres versions of the files. I've been meaning to create a GitHub action for it..

**Comment by chaoXO** [comment]
I just copy the files,hope it helps😂

**Comment by chaoXO** [comment]
I run the mimic-iv\concepts\convert_bigquery_to_postgres.sh ，and one sql file can't be converted correctly，
norepinephrine_equivalent_dose.sql 
}W QV 2_V_FSIUZM`0X$_XS

so I change the sql like
L RHM70BU6BK8M6}X7~0MBL

it can be run correctly,

so maybe there is some problem in mimic-iv\concepts\convert_bigquery_to_postgres.sh

**Pull request merged**
