### PR TITLE
Adding django helper files as well as solr setup helping files

### PR DESCRIPTION
**Pull request by horriblyUnpythonic**
This is work done for a project done at Georgia Tech in collaboration
with the FDA.

If you'd like any of this code moved, just let me know.

### CODE REVIEW

**Comment by tompollard** [comment]
@horriblyUnpythonic To help us decide how to incorporate the code, please could you describe the content and explain how it is intended to be used? Thanks, Tom

**Comment by horriblyUnpythonic** [comment]
There are two main contributions
First is some legwork done for a django project that maps to the database setup by the code in `bulidmimic`. This consists of the premade settings file and the file `etc/django_info/README.md` that oulines what was changed from the default. It also contains a `models.py` file that has been edited to more closely match the foreign key relations set up in the postgres db.

Second is some work for a solr instance config as well as a small python interface to query it. This allows for fast retrieval of documents in the note events table.

**Comment by cx1111** [comment]
Hello. I'm sorry for the great delay.

It seems like this is a rather large standalone project. Would you happen to have a github repo for this project by itself, with full documentation and such? It would be nice to see code content such as how you actually generated `models.py`.

**Comment by alistairewj** [comment]
Closing due to inactivity. Really appreciate the contribution, but we clearly never had the bandwidth to give this a proper review and incorporate it here. Highly recommend you create your own repo and add the mimic-iii tag!

**Pull request closed without merging**
