### PR TITLE
Fix docker build file for PostgreSQL

### PR DESCRIPTION
**Pull request by haobibo**

### CODE REVIEW

**Comment by xiaosongz** [comment]
Hi Haobibo,

Thanks a lot, I will check it out later this evening.

**Comment by alistairewj** [comment]
Thanks for the PR - I'll wait for @xiaosongz to give some feedback. Afterward let me know if I should test it!

**Comment by xiaosongz** [comment]
@haobibo It took some time to run due to re-importing the chartevents tables. It works find now on my Mac, Docker 2.2.0.3 and PostgreSQL 12.1-1.

**Comment by alistairewj** [comment]
Thanks! I will try it on Windows later but looks good to merge now.

**Pull request merged**
