### PR TITLE
Add initial mapping between itemid and loinc. ref #938.

### PR DESCRIPTION
**Pull request by a-chahin**
As discussed in issue #938, many of the LOINC mappings in the current version of MIMIC IV are not accurate. @Mauvila privately shared a spreadsheet with a number of improvements for the mappings. 

In the next version of MIMIC IV, we plan to remove the `loinc_code` column from `d_labitems` table. Instead the mappings will be provided as a table in the MIMIC code repository. This will allow the mapping to be improved over time.

This pull request adds an initial CSV file with itemid to loinc mapping codes that I think are correct. Using RELMA and clinical knowledge, I manually mapped and verified the LOINC codes. The information I used to make the mapping is `label`, `fluid`, `category`, `valueuom` from `d_labitems` and `labevents` tables.

I have not populated the rows with the mappings provided by @Mauvila, so that he is able to add his work in a separate pull request. I did not want to commit his work without his asking for his permission.

### CODE REVIEW

**Comment by tompollard** [comment]
Thanks @a-chahin! @alistairewj, let us know if you have thoughts about the file name, location, structure, etc.  All of the LOINCs listed here are ones where there is disagreement with the spreadsheet that we received. In most or all of the cases, I believe the issue relates to the fluid type. @xborrat is now doing a review of the mappings.

**Comment by alistairewj** [comment]
Looks good - I only have cosmetic thoughts

- why not under concepts? e.g. `concepts/mapping/` or `concepts/concept_map/` or something.
- I would include `itemid` in the filename e.g. `lab_itemid_to_loinc.csv`.
- Somewhere we should specify which version of LOINC we map to. Perhaps even another column, since future versions of LOINC may change the code meaning.

**Comment by xborrat** [comment]
Good job @a-chahin! I have checked one by one all the codes in the `loinc` column and found only 2 minor points to comment:

1/ In `itemid` 50937 which corresponds to "Antibody against hepatitis A virus" the units in the `valueuom` column appear N/A|Pos/Neg unlike the other  yes/no test where only N/A appears. 
2/ `itemid` 51094  which represents the urine pH it would be better to use 2756-5 which corresponds the generic concept of urinary pH than 5803-2 which is too specific concept because is the urine pH test strip.

**Comment by a-chahin** [comment]
> Looks good - I only have cosmetic thoughts
> 
> * why not under concepts? e.g. `concepts/mapping/` or `concepts/concept_map/` or something.
> * I would include `itemid` in the filename e.g. `lab_itemid_to_loinc.csv`.
> * Somewhere we should specify which version of LOINC we map to. Perhaps even another column, since future versions of LOINC may change the code meaning.

@alistairewj Thank you for the feedback! I'll start implementing the changes.

**Comment by a-chahin** [comment]
> Good job @a-chahin! I have checked one by one all the codes in the `loinc` column and found only 2 minor points to comment:
> 
> 1/ In `itemid` 50937 which corresponds to "Antibody against hepatitis A virus" the units in the `valueuom` column appear N/A|Pos/Neg unlike the other yes/no test where only N/A appears. 2/ `itemid` 51094 which represents the urine pH it would be better to use 2756-5 which corresponds the generic concept of urinary pH than 5803-2 which is too specific concept because is the urine pH test strip.

@xborrat Thank you for your feedback!

1/ Regarding the other yes/no tests that have N/A in the `valueuom` column, I checked the `value` column and found out that the values are NEG/POS. For example, `itemid`  50940 "Hepatitis B Surface Antibody" has a N/A in the `valueuom` column. When I ran a query for DISTINCT `value` I got "7.9/NEG/POS"
2/ Excellent point! I think you are right. 2756-5 is better since it does not specify the method. I selected 5803-2 because there is another `itemid` 51491 for Urine pH (but with a category of "Hematology" which is weird) that was mapped 5803-2, and 5803-2 has a higher rank on RELMA than 2756-5 so I assumed this is the most common method to test the pH of urine.

**Comment by alistairewj** [comment]
@a-chahin worth looking at #938 for some additional discussion

**Comment by a-chahin** [comment]
> @a-chahin worth looking at #938 for some additional discussion

Thank you, @alistairewj ! I think it is helpful to check with BIDMC regarding the LOINC mappings since Health Information Exchange (HIE) is one of the requirements of meaningful use stage 3.

**Comment by tompollard** [comment]
Thanks @a-chahin, this is a great start. We can follow up with additional LOINCs and updates to the structure as needed.

**Pull request merged**
