### PR TITLE
Analyzing glucose measurements and insulin inputs

### PR DESCRIPTION
**Pull request by lawbaker**

### CODE REVIEW

**Comment by alistairewj** [comment]
Accidental PR?

**Comment by lawbaker** [comment]
More that I messed up, I haven't used GitHub much. I have two files I want
to upload in a new folder, but when I created the folder I was unable to
upload.

**Comment by alistairewj** [comment]
You'll need to fork the repository, upload the folder/file to your fork, and then PR your repository to this one. GitHub tries to make the process simple if you are just uploading a single file but it doesn't work for multiple files.

**Comment by lawbaker** [comment]
Thanks, appreciate you walking me through. I think I've now done that
successfully.

Lawrence

**Pull request closed without merging**
